"""Specialised collector for E2 (codebook-size sweep). Produces:

  * results/e2_table.tex      -- the LaTeX tabular body for Table 4
  * results/e2_data.json      -- raw numbers for ad-hoc plotting
  * results/figures_paper/fig_codebook_scaling.png -- two-line plot

Reads TensorBoard event streams from the eight runs:
  cifar10_vanilla_K{1024,4096,8192,16384}_e2
  cifar10_rotent_K{1024,4096,8192,16384}_e2
"""

from __future__ import annotations
import glob, json, os
from collections import defaultdict
from pathlib import Path
import numpy as np
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator

RESULTS = Path(os.path.expanduser("~/vq-rotation/results"))
KS = [1024, 4096, 8192, 16384]


def load_run(name: str) -> dict | None:
    path = RESULTS / name / "tb"
    if not path.exists():
        return None
    data = defaultdict(list)
    for ev in sorted(glob.glob(str(path / "events.out.tfevents.*"))):
        try:
            acc = EventAccumulator(ev)
            acc.Reload()
            for tag in acc.Tags()["scalars"]:
                for e in acc.Scalars(tag):
                    data[tag].append((e.step, e.value))
        except Exception:
            continue
    out = {}
    for tag, pairs in data.items():
        pairs.sort()
        steps, vals = zip(*pairs)
        out[tag] = (np.array(steps), np.array(vals))
    return out


def final(run: dict, tag: str):
    if tag not in run:
        return None
    return float(run[tag][1][-1])


def main():
    rows = []
    raw = {}
    for K in KS:
        for method, prefix in [("vanilla", "vanilla"), ("rotent", "rotent")]:
            run = load_run(f"cifar10_{prefix}_K{K}_e2")
            if run is None:
                rows.append((method, K, None, None, None, None))
                continue
            psnr = final(run, "val/psnr")
            ssim = final(run, "val/ssim")
            usage = final(run, "val/usage")
            perp = final(run, "val/perplexity")
            rows.append((method, K, psnr, ssim, usage, perp))
            raw[f"{method}_K{K}"] = {
                "psnr": psnr,
                "ssim": ssim,
                "usage": usage,
                "perplexity": perp,
            }
            print(
                f"  {method:8s} K={K:5d}  PSNR={psnr if psnr else 'N/A'}  "
                f"usage={usage}  perp={perp}"
            )

    # --- LaTeX tabular body (one row per K, two methods side-by-side) ---
    def fmt(v, d=2):
        if v is None:
            return "??"
        return f"{v:.{d}f}"

    by_k = {K: {"vanilla": None, "rotent": None} for K in KS}
    for method, K, psnr, ssim, usage, perp in rows:
        by_k[K][method] = (psnr, ssim, usage, perp)

    lines = ["% Auto-generated by scripts/collect_e2.py"]
    lines.append(r"\begin{tabular}{rcccc|cccc}")
    lines.append(r"\toprule")
    lines.append(
        r" & \multicolumn{4}{c|}{VQ-VAE (STE)} & \multicolumn{4}{c}{\ours{} + entropy ($\lambda{=}3$)} \\"
    )
    lines.append(
        r"$K$ & PSNR$\uparrow$ & SSIM$\uparrow$ & Usage$\uparrow$ & Perp.$\uparrow$ "
        r" & PSNR$\uparrow$ & SSIM$\uparrow$ & Usage$\uparrow$ & Perp.$\uparrow$ \\"
    )
    lines.append(r"\midrule")
    for K in KS:
        v = by_k[K]["vanilla"]
        r = by_k[K]["rotent"]
        if v is None:
            v = (None,) * 4
        if r is None:
            r = (None,) * 4
        lines.append(
            f"{K} & {fmt(v[0])} & {fmt(v[1])} & {fmt(v[2], 3)} & {fmt(v[3])} "
            f"& {fmt(r[0])} & {fmt(r[1])} & {fmt(r[2], 3)} & {fmt(r[3])} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    out_tex = RESULTS / "e2_table.tex"
    out_tex.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {out_tex}")
    print(out_tex.read_text())

    out_json = RESULTS / "e2_data.json"
    out_json.write_text(json.dumps(raw, indent=2))
    print(f"\nWrote {out_json}")

    # --- two-line plot: PSNR vs log K ---
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        ks = np.array(KS, dtype=float)
        van_psnr = np.array(
            [
                by_k[K]["vanilla"][0]
                if by_k[K]["vanilla"] and by_k[K]["vanilla"][0] is not None
                else np.nan
                for K in KS
            ]
        )
        rot_psnr = np.array(
            [
                by_k[K]["rotent"][0]
                if by_k[K]["rotent"] and by_k[K]["rotent"][0] is not None
                else np.nan
                for K in KS
            ]
        )
        van_perp = np.array(
            [
                by_k[K]["vanilla"][3]
                if by_k[K]["vanilla"] and by_k[K]["vanilla"][3] is not None
                else np.nan
                for K in KS
            ]
        )
        rot_perp = np.array(
            [
                by_k[K]["rotent"][3]
                if by_k[K]["rotent"] and by_k[K]["rotent"][3] is not None
                else np.nan
                for K in KS
            ]
        )

        fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.2))
        axes[0].plot(ks, van_psnr, "o-", color="#1f77b4", label="VQ-VAE (STE)")
        axes[0].plot(
            ks, rot_psnr, "s-", color="#d62728", label=r"\textsc{RotationVQ}+entropy"
        )
        axes[0].set_xscale("log", base=2)
        axes[0].set_xticks(KS)
        axes[0].set_xticklabels([str(k) for k in KS])
        axes[0].set_xlabel("codebook size K")
        axes[0].set_ylabel("val PSNR (dB)")
        axes[0].grid(alpha=0.3)
        axes[0].legend(frameon=False, fontsize=9)

        axes[1].plot(ks, van_perp, "o-", color="#1f77b4", label="VQ-VAE (STE)")
        axes[1].plot(
            ks, rot_perp, "s-", color="#d62728", label=r"\textsc{RotationVQ}+entropy"
        )
        axes[1].plot(ks, ks, "--", color="gray", alpha=0.5, label="K (max)")
        axes[1].set_xscale("log", base=2)
        axes[1].set_yscale("log", base=2)
        axes[1].set_xticks(KS)
        axes[1].set_xticklabels([str(k) for k in KS])
        axes[1].set_xlabel("codebook size K")
        axes[1].set_ylabel("perplexity")
        axes[1].grid(alpha=0.3)
        axes[1].legend(frameon=False, fontsize=9)

        plt.tight_layout()
        out_png = RESULTS / "figures_paper" / "fig_codebook_scaling.png"
        out_png.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(out_png, dpi=180, bbox_inches="tight")
        plt.close()
        print(f"Wrote {out_png}")
    except Exception as e:
        print(f"plotting skipped: {e}")


if __name__ == "__main__":
    main()
